/**
 * What `plugin-kit new` writes, as pure functions returning file → text, so
 * the templates are tested on their own and the CLI only writes them.
 */

import { HOOK_EVENT_NAMES, type HookEventName } from '../common.js';

export type FileMap = Record<string, string>;

const TOOL_EVENTS: readonly string[] = ['PreToolUse', 'PostToolUse', 'PostToolUseFailure', 'PermissionRequest', 'PermissionDenied'];

/** `PreToolUse` → `pre-tool-use`. */
export function kebab(name: string): string {
    return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

export function isHookEvent(name: string): name is HookEventName {
    return (HOOK_EVENT_NAMES as readonly string[]).includes(name);
}

/**
 * A command hook: `<file>.ts` with a pure `handle(input)` and a guard that
 * runs it when executed, plus `<file>.test.ts`. Paths are relative to the
 * hooks folder.
 */
export function hookFiles(event: HookEventName): FileMap {
    const file = kebab(event);
    // WorktreeCreate must answer with a path; every other event may answer nothing.
    const body = event === 'WorktreeCreate'
        ? `    // Create the worktree here, then say where it is.\n    return { worktreePath: \`\${input.cwd}/../\${input.name}\` };`
        : '    return {};';
    const assertion = event === 'WorktreeCreate' ? `expect(result.payload).toBe('/tmp/../wt');` : 'expect(result.wasAllowed).toBe(true);';
    const mockArgs = event === 'WorktreeCreate' ? `{ name: 'wt' }` : '';
    return {
        [`${file}.ts`]: `#!/usr/bin/env node
/**
 * ${event} hook. Generated by \`plugin-kit new hook ${event}\`.
 *
 * The decision lives in \`handle\`: pure, so it's tested without stdin.
 * Run it with Node 22.18+ (or \`tsx\`); Claude Code runs it as the command
 * in settings.json.
 */
import { pathToFileURL } from 'node:url';
import { runHook, ${event}, type ${event}EmitOptions, type ${event}Input } from '@aeriondyseti/plugin-kit';

export function handle(input: ${event}Input): ${event}EmitOptions {
${body}
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    runHook(() => ${event}.emitOutput(handle(${event}.parse())));
}
`,
        [`${file}.test.ts`]: `import { describe, expect, it } from 'vitest';
import { ${event} } from '@aeriondyseti/plugin-kit';
import { mock${event}, testHook } from '@aeriondyseti/plugin-kit/testing';
import { handle } from './${file}.js';

describe('${event} hook', () => {
    it('answers a plain event', () => {
        const result = testHook(mock${event}(${mockArgs}), () => ${event}.emitOutput(handle(${event}.parse())));
        ${assertion}
    });

    // Record real payloads with \`plugin-kit record\`, then:
    //   for (const f of loadFixtures('.claude/fixtures', { event: '${event}' })) { ... }
});
`,
    };
}

/** The settings.json entry that runs a generated hook. */
export function hookSettings(event: HookEventName, command: string): string {
    const entry = TOOL_EVENTS.includes(event)
        ? { matcher: '*', hooks: [{ type: 'command', command }] }
        : { hooks: [{ type: 'command', command }] };
    return JSON.stringify({ hooks: { [event]: [entry] } }, null, 4);
}

export type KitMode = 'none' | 'kit' | 'vendor';

/**
 * A mod: manifest, hooks.json, a `register.tsx` with a slash command that
 * opens a pane, a tsconfig, a test, a README. With `kit` the pane draws
 * widgets through `$.kit`; with `vendor`, through a vendored kit.
 */
export function modFiles(name: string, kit: KitMode = 'none', author?: string): FileMap {
    const title = name.split(/[-_]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
    const widgets = `{ Status: { type: 'text', value: 'ready' }, Progress: { type: 'meter', value: 3, max: 10 } }`;
    const draw = {
        none: `    const { Box, Text } = $.ui.resolve(e)
    return (
      <Box flexDirection="column">
        <Text bold>Hello from ${name}</Text>
        <Text dimColor>Edit hooks/register.tsx</Text>
      </Box>
    )`,
        kit: `    const { Box } = $.ui.resolve(e)
    const tree = await $.kit.render({ id: \`${name}:\${e.requestId}\`, widgets: ${widgets} })
    return <Box>{hydrate(tree, h)}</Box>`,
        vendor: `    const { Box } = $.ui.resolve(e)
    const tree = describeWidgets(${widgets}, { id: \`${name}:\${e.requestId}\` })
    return <Box>{hydrate(tree, h)}</Box>`,
    }[kit];
    const imports = {
        none: '',
        kit: `import { hydrate } from './hydrate.ts'\n`,
        vendor: `import { describeWidgets, hydrate } from './kit/index.ts'\n`,
    }[kit];
    const expectText = kit === 'none' ? `/Hello from ${name}/` : '/Progress/';

    return {
        '.claude-plugin/plugin.json': `${JSON.stringify({
            name,
            version: '0.1.0',
            description: `${title}: a Claude Code mod`,
            ...(author ? { author: { name: author } } : {}),
        }, null, 2)}\n`,
        'hooks/hooks.json': `${JSON.stringify({ modules: ['./register.tsx'] }, null, 2)}\n`,
        'hooks/register.tsx': `import type { Register } from 'claude-code'
${imports}
const PANE = '${name}'

export const register: Register = on => {
  on('session.start', async ($, e, next) => {
    await $.command.register({ name: '${name}', description: 'Open the ${title} pane' })
    return next(e)
  })

  on('command.run', { command: '${name}' }, async $ => {
    await $.ui.open({ id: PANE, title: '${title}' })
    return { text: '${title} pane opened.' }
  })

  on('ui.render', { component: 'Pane', requestId: PANE }, async ($, e) => {
${draw}
  })
}
`,
        [`tests/${name}.test.tsx`]: `import { expect, test } from 'claude-code/testing'
import { ${kit === 'kit' ? 'kitStub, ' : ''}mountTarget, SURFACES } from './kit-testing/index.ts'

test('the pane draws on every surface', ${kit === 'kit' ? '{ plugins: [kitStub] }, ' : ''}async $ => {
  for (const surface of SURFACES) {
    const ui = await $.ui.mount(mountTarget('${name}', 'Pane', surface, { title: '${title}' }, '${name}'))
    expect(await ui.find({ type: 'Text', text: ${expectText} })).toBeDefined()
    await ui.unmount()
  }
})
`,
        'tsconfig.json': `{
  "extends": "./.claude-plugin/types/tsconfig.json",
  "compilerOptions": { "allowImportingTsExtensions": true }
}
`,
        '.gitignore': '# Written by Claude Code whenever it loads the mod\n.claude-plugin/types/\n',
        'README.md': `# ${title}

A Claude Code mod. Generated by \`plugin-kit new mod ${name}\`.

\`\`\`sh
claude --plugin-dir .           # load it; then /${name} opens its pane
claude plugin validate .        # what the engine would refuse
claude plugin test .            # tests/, against Claude Code itself
npx tsc -p .                    # types, once Claude Code has loaded it once
npx @aeriondyseti/plugin-kit doctor .
\`\`\`
`,
    };
}
