/**
 * Fixtures: real hook payloads saved to disk and fed back to a hook later.
 *
 * `plugin-kit record` (a command hook) saves what Claude Code sends; tests
 * and `plugin-kit run` load it again. A fixture is the payload exactly as
 * Claude Code wrote it, one JSON file per call, filed by event:
 *
 *   fixtures/PreToolUse/20261006-142233-Bash.json
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

export interface Fixture {
    /** Where it was loaded from. */
    path: string;
    /** `hook_event_name`, or `unknown` when the payload has none. */
    event: string;
    /** The payload as Claude Code sent it. */
    input: Record<string, unknown>;
}

/**
 * Saves one payload under `<dir>/<Event>/<timestamp>-<label>.json` and
 * returns the path. The label is the tool, source or trigger when the event
 * has one, so a folder listing reads like a log.
 */
export function recordFixture(payload: string, dir: string, now = new Date()): string {
    const input = parseObject(payload, 'the payload');
    const event = typeof input.hook_event_name === 'string' ? input.hook_event_name : 'unknown';
    const label = [input.tool_name, input.source, input.trigger, input.matcher]
        .find((v): v is string => typeof v === 'string' && v !== '');
    const stamp = now.toISOString().replace(/[-:]/g, '').replace('T', '-').slice(0, 15);
    const folder = join(dir, safe(event));
    mkdirSync(folder, { recursive: true });
    let path = join(folder, `${stamp}${label ? `-${safe(label)}` : ''}.json`);
    for (let n = 2; exists(path); n++) path = path.replace(/(-\d+)?\.json$/, `-${n}.json`);
    writeFileSync(path, `${JSON.stringify(input, null, 2)}\n`);
    return path;
}

/** One fixture file. Throws when it isn't a JSON object. */
export function loadFixture(path: string): Fixture {
    const input = parseObject(readFileSync(path, 'utf8'), path);
    return { path, event: typeof input.hook_event_name === 'string' ? input.hook_event_name : 'unknown', input };
}

/**
 * Every `*.json` fixture under `dir` (recursively), sorted by path, so by
 * event then time. `event` keeps only that event's.
 */
export function loadFixtures(dir: string, opts: { event?: string } = {}): Fixture[] {
    return walk(dir)
        .filter((path) => path.endsWith('.json'))
        .sort()
        .map(loadFixture)
        .filter((fixture) => opts.event === undefined || fixture.event === opts.event);
}

/**
 * Fixtures as a TypeScript module, for mod tests: `claude plugin test` runs
 * them where there is no file system, but a `.ts` file can be imported.
 */
export function fixturesModule(fixtures: readonly Fixture[], baseDir: string): string {
    const entries = fixtures.map((f) => `    ${JSON.stringify(relative(baseDir, f.path).replaceAll('\\', '/'))}: ${JSON.stringify(f.input)},`);
    return [
        '// Generated by `plugin-kit fixtures`. Do not edit; record and generate again.',
        '',
        'export const fixtures = {',
        ...entries,
        '} as const;',
        '',
    ].join('\n');
}

function walk(dir: string): string[] {
    return readdirSync(dir).flatMap((name) => {
        const path = join(dir, name);
        return statSync(path).isDirectory() ? walk(path) : [path];
    });
}

function parseObject(text: string, what: string): Record<string, unknown> {
    let value: unknown;
    try {
        value = JSON.parse(text);
    } catch {
        throw new Error(`${what} is not JSON`);
    }
    if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error(`${what} is not a JSON object`);
    return value as Record<string, unknown>;
}

function safe(name: string): string {
    return name.replace(/[^\w.-]+/g, '_').slice(0, 60);
}

function exists(path: string): boolean {
    try {
        statSync(path);
        return true;
    } catch {
        return false;
    }
}
